spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/english-sentences
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    spring:
      banner:
        location: classpath:banner.txt

security-config:
  open1: /api/v1/open/**
  testvar: mytestvar1



#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/jwt_security
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#      ddl-auto: update